#ifndef ASSETS_H
#define ASSETS_H

extern const unsigned int tex_actor_BLOB2[];
extern const unsigned int tex_actor_demon[];
extern const unsigned int tex_actor_iq[];
extern const unsigned int tex_actor_key[];
extern const unsigned int tex_actor_monster1[];
extern const unsigned int tex_actor_monster2[];
extern const unsigned int tex_actor_monster3[];

extern const unsigned int tex_interface_barrel[];
extern const unsigned int tex_interface_font[];
extern const unsigned int tex_interface_icon[];

extern const unsigned int tex_level_bricks[];
extern const unsigned int tex_level_cross[];
extern const unsigned int tex_level_wall2[];
#endif
// Automatically generated by genassets.py
