#ifndef ASSETS_H
#define ASSETS_H

extern const unsigned char gztex_actor_BLOB2[];
extern const unsigned char gztex_actor_demon[];
extern const unsigned char gztex_actor_iq[];
extern const unsigned char gztex_actor_key[];
extern const unsigned char gztex_actor_monster1[];
extern const unsigned char gztex_actor_monster2[];
extern const unsigned char gztex_actor_monster3[];

extern const unsigned char gzsnd_audio_field[];

extern const unsigned char gztex_interface_barrel[];
extern const unsigned char gztex_interface_font[];
extern const unsigned char gztex_interface_icon[];

extern const unsigned char gztex_level_bricks[];
extern const unsigned char gztex_level_cross[];
extern const unsigned char gztex_level_sky[];
extern const unsigned char gztex_level_smile[];
extern const unsigned char gztex_level_wall2[];


#define ASSET_COUNT 16

#endif
// Automatically generated by genassets.py
